### ISSUE TITLE
Consider exposing named colors map

### ISSUE THREAD

**Issue by g-plane** [mazznoer/csscolorparser-rs#8]
There's a case for me that I need to convert RGB value to named color back (if it's available), but this crate doesn't expose that named colors map so I can't do it. Is there a plan that considering exposing it?

**Comment by mazznoer** [comment]
I added a new `Color`'s method `name()` that will return color name if it's available.

```rust
assert_eq!(Color::from_rgba8(255, 0, 0, 255).name().unwrap(), "red");
```

Is it sufficient for your needs?

**Comment by g-plane** [comment]
I've checked the commit: https://github.com/mazznoer/csscolorparser-rs/commit/20ef912ba1bd452af2eb951abb310ad87b55d83e . Would it be better that using `Option` instead of `Result`? For my opinion, it means "whether there's a name for such color or not", not an error about missing name.

**Comment by mazznoer** [comment]
I agree with you.
